function plotGeneCountsGalaxy
%% Function written by Eleni Christoforidou in MATLAB R2019b

%This function creates plots for the top 6 most upregulated and the top 6
%most downregulated genes, using data generated by DESeq2. The plots show
%the number of times each gene is present in each sample, separated by
%group.

%Run this function from inside the folder containing the CSV files 
%outputted by DESeq2.

%This function also requires a TXT file outputted by featureCounts on 
%Galaxy, which contains the counts for each gene in the last N columns, 
%where N is equal to the number of samples. In this function, N is 
%hardcoded as equal to 6.

%INPUT ARGUMENTS: None.

%OUTPUT ARGUMENTS: None, but the plot is saved in 2 different formats in
%the working directory.

%% Load data.
counts=readtable('symbol_counts.txt','FileType','text'); %load featureCounts results.
down=readtable('symbolGroup_mutant_vs_wildtype_resDown.csv','FileType','text'); %load downregulated genes.
up=readtable('symbolGroup_mutant_vs_wildtype_resUp.csv','FileType','text'); %load upregulated genes.

down=sortrows(down,'log2FoldChange','ascend'); %sort genes from most downregulated to least downregulated.
up=sortrows(up,'log2FoldChange','descend'); %sort genes from most upregulated to least upregulated.

down6=table2cell(down(1:6,1)); %get 6 most downregulated genes.
up6=table2cell(up(1:6,1)); %get 6 most upregulated genes.

%Initialise variables.
geneIDsDown=cell(6,1);
geneIDsUp=cell(6,1);
downCounts=zeros(6,6);
upCounts=zeros(6,6);
jj=1;
kk=1;

for ii=1:height(counts) %loop through each gene.
    geneID=table2cell(counts(ii,1)); %get gene name.
    if ismember(num2str(geneID{1}),down6)
        geneIDsDown{jj}=geneID; %get name of current gene.
        downCounts(jj,:)=table2array(counts(ii,2:7)); %get number of counts for current gene for each sample.
        jj=jj+1;
    end
    if ismember(num2str(geneID{1}),up6)
        geneIDsUp{kk}=geneID;
        upCounts(kk,:)=table2array(counts(ii,2:7));
        kk=kk+1;
    end
end

%% PLOT DOWNREGULATED GENES.

%Subplot 1.
fig=figure('Position', get(0, 'Screensize')); %make figure full-screen.
ax(1)=subplot(2,3,1);
dataWT=downCounts(1,1:3);
dataMT=downCounts(1,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
x1=ones(1,length(dataWT));
x2=2*ones(1,length(dataMT));
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(1).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{1},'FontSize',12); %add plot title.
ax(1).XAxis.FontSize=12; %set x-axis fontsize.
ax(1).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
hold off;

%Subplot 2.
ax(2)=subplot(2,3,2);
dataWT=downCounts(2,1:3);
dataMT=downCounts(2,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(2).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{2},'FontSize',12); %add plot title.
ax(2).XAxis.FontSize=12; %set x-axis fontsize.
ax(2).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 3.
ax(3)=subplot(2,3,3);
dataWT=downCounts(3,1:3);
dataMT=downCounts(3,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(3).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{3},'FontSize',12); %add plot title.
ax(3).XAxis.FontSize=12; %set x-axis fontsize.
ax(3).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 4.
ax(4)=subplot(2,3,4);
dataWT=downCounts(4,1:3);
dataMT=downCounts(4,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(4).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{4},'FontSize',12); %add plot title.
ax(4).XAxis.FontSize=12; %set x-axis fontsize.
ax(4).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 5.
ax(5)=subplot(2,3,5);
dataWT=downCounts(5,1:3);
dataMT=downCounts(5,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(5).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{5},'FontSize',12); %add plot title.
ax(5).XAxis.FontSize=12; %set x-axis fontsize.
ax(5).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
hold off;

%Subplot 6.
ax(6)=subplot(2,3,6);
dataWT=downCounts(6,1:3);
dataMT=downCounts(6,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(6).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{6},'FontSize',12); %add plot title.
ax(6).XAxis.FontSize=12; %set x-axis fontsize.
ax(6).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Save plot.
savefig(fig,'geneCountsUp'); %save figure as a FIG file in the working directory.
fig.Renderer='painters'; %force MATLAB to render the image as a vector.
saveas(fig,'geneCountsUp.svg'); %save figure as an SVG file.
close

%% PLOT UPREGULATED GENES.

%Subplot 1.
fig=figure('Position', get(0, 'Screensize')); %make figure full-screen.
ax(1)=subplot(2,3,1);
dataWT=upCounts(1,1:3);
dataMT=upCounts(1,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
x1=ones(1,length(dataWT));
x2=2*ones(1,length(dataMT));
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(1).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsUp{1},'FontSize',12); %add plot title.
ax(1).XAxis.FontSize=12; %set x-axis fontsize.
ax(1).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 2.
ax(2)=subplot(2,3,2);
dataWT=upCounts(2,1:3);
dataMT=upCounts(2,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(2).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsDown{2},'FontSize',12); %add plot title.
ax(2).XAxis.FontSize=12; %set x-axis fontsize.
ax(2).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 3.
ax(3)=subplot(2,3,3);
dataWT=upCounts(3,1:3);
dataMT=upCounts(3,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(3).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsUp{3},'FontSize',12); %add plot title.
ax(3).XAxis.FontSize=12; %set x-axis fontsize.
ax(3).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 4.
ax(4)=subplot(2,3,4);
dataWT=upCounts(4,1:3);
dataMT=upCounts(4,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(4).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsUp{4},'FontSize',12); %add plot title.
ax(4).XAxis.FontSize=12; %set x-axis fontsize.
ax(4).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 5.
ax(5)=subplot(2,3,5);
dataWT=upCounts(5,1:3);
dataMT=upCounts(5,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(5).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsUp{5},'FontSize',12); %add plot title.
ax(5).XAxis.FontSize=12; %set x-axis fontsize.
ax(5).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Subplot 6.
ax(6)=subplot(2,3,6);
dataWT=upCounts(6,1:3);
dataMT=upCounts(6,4:6);
meanWT=mean(dataWT); %calculate the mean for wildtypes.
meanMT=mean(dataMT); %calculate the mean for mutants.
plot(x1,dataWT,'b.','MarkerSize',20); %plot wildyptes.
hold on;
plot(x1,meanWT,'kx','MarkerSize',12); %plot mean for wildtypes.
plot(x2,dataMT,'r.','MarkerSize',20); %plot mutants.
plot(x2,meanMT,'kx','MarkerSize',12); %plot mean for mutants.
set(gca,'box','off'); %remove top x-axis and right y-axis.
xlim([0 3]);
ylabel('Count','FontSize',12); %add y-axis label.
ax(6).XTickLabels={'','','Wildtype','','Mutant','',''};
title(geneIDsUp{6},'FontSize',12); %add plot title.
ax(6).XAxis.FontSize=12; %set x-axis fontsize.
ax(6).YAxis.FontSize=12; %set y-axis fontsize.
grid on;
yy=ylim;
ylim([yy(1) yy(2)+2]);
hold off;

%Save plot.
savefig(fig,'geneCountsDown'); %save figure as a FIG file in the working directory.
fig.Renderer='painters'; %force MATLAB to render the image as a vector.
saveas(fig,'geneCountsDown.svg'); %save figure as an SVG file.
close
clear
end